/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.search.verification.client;

public final class R {
    public static final class attr {
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int alpha=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int coordinatorLayoutStyle=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int font=0x7f010011;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fontProviderAuthority=0x7f01000a;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int fontProviderCerts=0x7f01000d;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>blocking</code></td><td>0</td><td></td></tr>
<tr><td><code>async</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int fontProviderFetchStrategy=0x7f01000e;
        /** <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>forever</code></td><td>-1</td><td></td></tr>
</table>
         */
        public static int fontProviderFetchTimeout=0x7f01000f;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fontProviderPackage=0x7f01000b;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fontProviderQuery=0x7f01000c;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>italic</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int fontStyle=0x7f010010;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fontVariationSettings=0x7f010013;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fontWeight=0x7f010012;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int keylines=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int layout_anchor=0x7f010005;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>center_vertical</code></td><td>0x10</td><td></td></tr>
<tr><td><code>fill_vertical</code></td><td>0x70</td><td></td></tr>
<tr><td><code>center_horizontal</code></td><td>0x01</td><td></td></tr>
<tr><td><code>fill_horizontal</code></td><td>0x07</td><td></td></tr>
<tr><td><code>center</code></td><td>0x11</td><td></td></tr>
<tr><td><code>fill</code></td><td>0x77</td><td></td></tr>
<tr><td><code>clip_vertical</code></td><td>0x80</td><td></td></tr>
<tr><td><code>clip_horizontal</code></td><td>0x08</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
         */
        public static int layout_anchorGravity=0x7f010007;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int layout_behavior=0x7f010004;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0x0</td><td></td></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
<tr><td><code>all</code></td><td>0x77</td><td></td></tr>
</table>
         */
        public static int layout_dodgeInsetEdges=0x7f010009;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0x0</td><td></td></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
         */
        public static int layout_insetEdge=0x7f010008;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int layout_keyline=0x7f010006;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int statusBarBackground=0x7f010003;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int ttcIndex=0x7f010014;
    }
    public static final class color {
        public static int notification_action_color_filter=0x7f040000;
        public static int notification_icon_bg_color=0x7f040001;
        public static int notification_material_background_media_default_color=0x7f040002;
        public static int primary_text_default_material_dark=0x7f040003;
        public static int ripple_material_light=0x7f040004;
        public static int secondary_text_default_material_dark=0x7f040005;
        public static int secondary_text_default_material_light=0x7f040006;
    }
    public static final class dimen {
        public static int compat_button_inset_horizontal_material=0x7f050000;
        public static int compat_button_inset_vertical_material=0x7f050001;
        public static int compat_button_padding_horizontal_material=0x7f050002;
        public static int compat_button_padding_vertical_material=0x7f050003;
        public static int compat_control_corner_material=0x7f050004;
        public static int compat_notification_large_icon_max_height=0x7f050005;
        public static int compat_notification_large_icon_max_width=0x7f050006;
        public static int notification_action_icon_size=0x7f050007;
        public static int notification_action_text_size=0x7f050008;
        public static int notification_big_circle_margin=0x7f050009;
        public static int notification_content_margin_start=0x7f05000a;
        public static int notification_large_icon_height=0x7f05000b;
        public static int notification_large_icon_width=0x7f05000c;
        public static int notification_main_column_padding_top=0x7f05000d;
        public static int notification_media_narrow_margin=0x7f05000e;
        public static int notification_right_icon_size=0x7f05000f;
        public static int notification_right_side_padding_top=0x7f050010;
        public static int notification_small_icon_background_padding=0x7f050011;
        public static int notification_small_icon_size_as_large=0x7f050012;
        public static int notification_subtext_size=0x7f050013;
        public static int notification_top_pad=0x7f050014;
        public static int notification_top_pad_large_text=0x7f050015;
        public static int subtitle_corner_radius=0x7f050016;
        public static int subtitle_outline_width=0x7f050017;
        public static int subtitle_shadow_offset=0x7f050018;
        public static int subtitle_shadow_radius=0x7f050019;
    }
    public static final class drawable {
        public static int notification_action_background=0x7f020000;
        public static int notification_bg=0x7f020001;
        public static int notification_bg_low=0x7f020002;
        public static int notification_bg_low_normal=0x7f020003;
        public static int notification_bg_low_pressed=0x7f020004;
        public static int notification_bg_normal=0x7f020005;
        public static int notification_bg_normal_pressed=0x7f020006;
        public static int notification_icon_background=0x7f020007;
        public static int notification_template_icon_bg=0x7f02000a;
        public static int notification_template_icon_low_bg=0x7f02000b;
        public static int notification_tile_bg=0x7f020008;
        public static int notify_panel_notification_icon_bg=0x7f020009;
    }
    public static final class id {
        public static int action0=0x7f060023;
        public static int action_container=0x7f060020;
        public static int action_divider=0x7f060027;
        public static int action_image=0x7f060021;
        public static int action_text=0x7f060022;
        public static int actions=0x7f060031;
        public static int all=0x7f06001a;
        public static int async=0x7f06001b;
        public static int blocking=0x7f06001c;
        public static int bottom=0x7f06000b;
        public static int cancel_action=0x7f060024;
        public static int center=0x7f06000c;
        public static int center_horizontal=0x7f06000d;
        public static int center_vertical=0x7f06000e;
        public static int chronometer=0x7f06002c;
        public static int clip_horizontal=0x7f06000f;
        public static int clip_vertical=0x7f060010;
        public static int end=0x7f060011;
        public static int end_padder=0x7f060033;
        public static int fill=0x7f060012;
        public static int fill_horizontal=0x7f060013;
        public static int fill_vertical=0x7f060014;
        public static int forever=0x7f06001d;
        public static int icon=0x7f06002e;
        public static int icon_group=0x7f060032;
        public static int info=0x7f06002d;
        public static int italic=0x7f06001e;
        public static int left=0x7f060015;
        public static int line1=0x7f060000;
        public static int line3=0x7f060001;
        public static int media_actions=0x7f060026;
        public static int none=0x7f060019;
        public static int normal=0x7f06001f;
        public static int notification_background=0x7f060030;
        public static int notification_main_column=0x7f060029;
        public static int notification_main_column_container=0x7f060028;
        public static int right=0x7f060016;
        public static int right_icon=0x7f06002f;
        public static int right_side=0x7f06002a;
        public static int start=0x7f060017;
        public static int status_bar_latest_event_content=0x7f060025;
        public static int tag_accessibility_heading=0x7f060002;
        public static int tag_accessibility_pane_title=0x7f060003;
        public static int tag_screen_reader_focusable=0x7f060004;
        public static int tag_transition_group=0x7f060005;
        public static int tag_unhandled_key_event_manager=0x7f060006;
        public static int tag_unhandled_key_listeners=0x7f060007;
        public static int text=0x7f060008;
        public static int text2=0x7f060009;
        public static int time=0x7f06002b;
        public static int title=0x7f06000a;
        public static int top=0x7f060018;
    }
    public static final class integer {
        public static int cancel_button_image_alpha=0x7f070000;
        public static int status_bar_notification_info_maxnum=0x7f070001;
    }
    public static final class layout {
        public static int notification_action=0x7f030000;
        public static int notification_action_tombstone=0x7f030001;
        public static int notification_media_action=0x7f030002;
        public static int notification_media_cancel_action=0x7f030003;
        public static int notification_template_big_media=0x7f030004;
        public static int notification_template_big_media_custom=0x7f030005;
        public static int notification_template_big_media_narrow=0x7f030006;
        public static int notification_template_big_media_narrow_custom=0x7f030007;
        public static int notification_template_custom_big=0x7f030008;
        public static int notification_template_icon_group=0x7f030009;
        public static int notification_template_lines_media=0x7f03000a;
        public static int notification_template_media=0x7f03000b;
        public static int notification_template_media_custom=0x7f03000c;
        public static int notification_template_part_chronometer=0x7f03000d;
        public static int notification_template_part_time=0x7f03000e;
    }
    public static final class string {
        public static int google_assistant_verification_channel_name=0x7f080000;
        public static int google_assistant_verification_notification_title=0x7f080001;
        public static int status_bar_notification_info_overflow=0x7f080002;
    }
    public static final class style {
        public static int TextAppearance_Compat_Notification=0x7f090000;
        public static int TextAppearance_Compat_Notification_Info=0x7f090001;
        public static int TextAppearance_Compat_Notification_Info_Media=0x7f090002;
        public static int TextAppearance_Compat_Notification_Line2=0x7f090003;
        public static int TextAppearance_Compat_Notification_Line2_Media=0x7f090004;
        public static int TextAppearance_Compat_Notification_Media=0x7f090005;
        public static int TextAppearance_Compat_Notification_Time=0x7f090006;
        public static int TextAppearance_Compat_Notification_Time_Media=0x7f090007;
        public static int TextAppearance_Compat_Notification_Title=0x7f090008;
        public static int TextAppearance_Compat_Notification_Title_Media=0x7f090009;
        public static int Widget_Compat_NotificationActionContainer=0x7f09000a;
        public static int Widget_Compat_NotificationActionText=0x7f09000b;
        public static int Widget_Support_CoordinatorLayout=0x7f09000c;
    }
    public static final class styleable {
        /** Attributes that can be used with a ColorStateListItem.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ColorStateListItem_alpha com.google.android.search.verification.client:alpha}</code></td><td></td></tr>
           <tr><td><code>{@link #ColorStateListItem_android_alpha android:alpha}</code></td><td></td></tr>
           <tr><td><code>{@link #ColorStateListItem_android_color android:color}</code></td><td></td></tr>
           </table>
           @see #ColorStateListItem_alpha
           @see #ColorStateListItem_android_alpha
           @see #ColorStateListItem_android_color
         */
        public static final int[] ColorStateListItem = {
            0x010101a5, 0x0101031f, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#alpha}
          attribute's value can be found in the {@link #ColorStateListItem} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:alpha
        */
        public static int ColorStateListItem_alpha = 2;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#alpha}
          attribute's value can be found in the {@link #ColorStateListItem} array.
          @attr name android:alpha
        */
        public static int ColorStateListItem_android_alpha = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#color}
          attribute's value can be found in the {@link #ColorStateListItem} array.
          @attr name android:color
        */
        public static int ColorStateListItem_android_color = 0;
        /** Attributes that can be used with a CoordinatorLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CoordinatorLayout_keylines com.google.android.search.verification.client:keylines}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_statusBarBackground com.google.android.search.verification.client:statusBarBackground}</code></td><td></td></tr>
           </table>
           @see #CoordinatorLayout_keylines
           @see #CoordinatorLayout_statusBarBackground
         */
        public static final int[] CoordinatorLayout = {
            0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#keylines}
          attribute's value can be found in the {@link #CoordinatorLayout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.google.android.search.verification.client:keylines
        */
        public static int CoordinatorLayout_keylines = 0;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#statusBarBackground}
          attribute's value can be found in the {@link #CoordinatorLayout} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.google.android.search.verification.client:statusBarBackground
        */
        public static int CoordinatorLayout_statusBarBackground = 1;
        /** Attributes that can be used with a CoordinatorLayout_Layout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_android_layout_gravity android:layout_gravity}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_anchor com.google.android.search.verification.client:layout_anchor}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_anchorGravity com.google.android.search.verification.client:layout_anchorGravity}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_behavior com.google.android.search.verification.client:layout_behavior}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_dodgeInsetEdges com.google.android.search.verification.client:layout_dodgeInsetEdges}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_insetEdge com.google.android.search.verification.client:layout_insetEdge}</code></td><td></td></tr>
           <tr><td><code>{@link #CoordinatorLayout_Layout_layout_keyline com.google.android.search.verification.client:layout_keyline}</code></td><td></td></tr>
           </table>
           @see #CoordinatorLayout_Layout_android_layout_gravity
           @see #CoordinatorLayout_Layout_layout_anchor
           @see #CoordinatorLayout_Layout_layout_anchorGravity
           @see #CoordinatorLayout_Layout_layout_behavior
           @see #CoordinatorLayout_Layout_layout_dodgeInsetEdges
           @see #CoordinatorLayout_Layout_layout_insetEdge
           @see #CoordinatorLayout_Layout_layout_keyline
         */
        public static final int[] CoordinatorLayout_Layout = {
            0x010100b3, 0x7f010004, 0x7f010005, 0x7f010006,
            0x7f010007, 0x7f010008, 0x7f010009
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#layout_gravity}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.
          @attr name android:layout_gravity
        */
        public static int CoordinatorLayout_Layout_android_layout_gravity = 0;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_anchor}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.google.android.search.verification.client:layout_anchor
        */
        public static int CoordinatorLayout_Layout_layout_anchor = 2;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_anchorGravity}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>center_vertical</code></td><td>0x10</td><td></td></tr>
<tr><td><code>fill_vertical</code></td><td>0x70</td><td></td></tr>
<tr><td><code>center_horizontal</code></td><td>0x01</td><td></td></tr>
<tr><td><code>fill_horizontal</code></td><td>0x07</td><td></td></tr>
<tr><td><code>center</code></td><td>0x11</td><td></td></tr>
<tr><td><code>fill</code></td><td>0x77</td><td></td></tr>
<tr><td><code>clip_vertical</code></td><td>0x80</td><td></td></tr>
<tr><td><code>clip_horizontal</code></td><td>0x08</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:layout_anchorGravity
        */
        public static int CoordinatorLayout_Layout_layout_anchorGravity = 4;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_behavior}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:layout_behavior
        */
        public static int CoordinatorLayout_Layout_layout_behavior = 1;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_dodgeInsetEdges}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0x0</td><td></td></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
<tr><td><code>all</code></td><td>0x77</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:layout_dodgeInsetEdges
        */
        public static int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_insetEdge}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0x0</td><td></td></tr>
<tr><td><code>top</code></td><td>0x30</td><td></td></tr>
<tr><td><code>bottom</code></td><td>0x50</td><td></td></tr>
<tr><td><code>left</code></td><td>0x03</td><td></td></tr>
<tr><td><code>right</code></td><td>0x05</td><td></td></tr>
<tr><td><code>start</code></td><td>0x00800003</td><td></td></tr>
<tr><td><code>end</code></td><td>0x00800005</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:layout_insetEdge
        */
        public static int CoordinatorLayout_Layout_layout_insetEdge = 5;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#layout_keyline}
          attribute's value can be found in the {@link #CoordinatorLayout_Layout} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:layout_keyline
        */
        public static int CoordinatorLayout_Layout_layout_keyline = 3;
        /** Attributes that can be used with a FontFamily.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FontFamily_fontProviderAuthority com.google.android.search.verification.client:fontProviderAuthority}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamily_fontProviderCerts com.google.android.search.verification.client:fontProviderCerts}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamily_fontProviderFetchStrategy com.google.android.search.verification.client:fontProviderFetchStrategy}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamily_fontProviderFetchTimeout com.google.android.search.verification.client:fontProviderFetchTimeout}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamily_fontProviderPackage com.google.android.search.verification.client:fontProviderPackage}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamily_fontProviderQuery com.google.android.search.verification.client:fontProviderQuery}</code></td><td></td></tr>
           </table>
           @see #FontFamily_fontProviderAuthority
           @see #FontFamily_fontProviderCerts
           @see #FontFamily_fontProviderFetchStrategy
           @see #FontFamily_fontProviderFetchTimeout
           @see #FontFamily_fontProviderPackage
           @see #FontFamily_fontProviderQuery
         */
        public static final int[] FontFamily = {
            0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d,
            0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderAuthority}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:fontProviderAuthority
        */
        public static int FontFamily_fontProviderAuthority = 0;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderCerts}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.google.android.search.verification.client:fontProviderCerts
        */
        public static int FontFamily_fontProviderCerts = 3;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderFetchStrategy}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>blocking</code></td><td>0</td><td></td></tr>
<tr><td><code>async</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:fontProviderFetchStrategy
        */
        public static int FontFamily_fontProviderFetchStrategy = 4;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderFetchTimeout}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>forever</code></td><td>-1</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:fontProviderFetchTimeout
        */
        public static int FontFamily_fontProviderFetchTimeout = 5;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderPackage}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:fontProviderPackage
        */
        public static int FontFamily_fontProviderPackage = 1;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontProviderQuery}
          attribute's value can be found in the {@link #FontFamily} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:fontProviderQuery
        */
        public static int FontFamily_fontProviderQuery = 2;
        /** Attributes that can be used with a FontFamilyFont.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FontFamilyFont_android_font android:font}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_android_fontStyle android:fontStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_android_fontVariationSettings android:fontVariationSettings}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_android_fontWeight android:fontWeight}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_android_ttcIndex android:ttcIndex}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_font com.google.android.search.verification.client:font}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_fontStyle com.google.android.search.verification.client:fontStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_fontVariationSettings com.google.android.search.verification.client:fontVariationSettings}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_fontWeight com.google.android.search.verification.client:fontWeight}</code></td><td></td></tr>
           <tr><td><code>{@link #FontFamilyFont_ttcIndex com.google.android.search.verification.client:ttcIndex}</code></td><td></td></tr>
           </table>
           @see #FontFamilyFont_android_font
           @see #FontFamilyFont_android_fontStyle
           @see #FontFamilyFont_android_fontVariationSettings
           @see #FontFamilyFont_android_fontWeight
           @see #FontFamilyFont_android_ttcIndex
           @see #FontFamilyFont_font
           @see #FontFamilyFont_fontStyle
           @see #FontFamilyFont_fontVariationSettings
           @see #FontFamilyFont_fontWeight
           @see #FontFamilyFont_ttcIndex
         */
        public static final int[] FontFamilyFont = {
            0x01010532, 0x01010533, 0x0101053f, 0x0101056f,
            0x01010570, 0x7f010010, 0x7f010011, 0x7f010012,
            0x7f010013, 0x7f010014
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#font}
          attribute's value can be found in the {@link #FontFamilyFont} array.
          @attr name android:font
        */
        public static int FontFamilyFont_android_font = 0;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#fontStyle}
          attribute's value can be found in the {@link #FontFamilyFont} array.
          @attr name android:fontStyle
        */
        public static int FontFamilyFont_android_fontStyle = 2;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#fontVariationSettings}
          attribute's value can be found in the {@link #FontFamilyFont} array.
          @attr name android:fontVariationSettings
        */
        public static int FontFamilyFont_android_fontVariationSettings = 4;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#fontWeight}
          attribute's value can be found in the {@link #FontFamilyFont} array.
          @attr name android:fontWeight
        */
        public static int FontFamilyFont_android_fontWeight = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#ttcIndex}
          attribute's value can be found in the {@link #FontFamilyFont} array.
          @attr name android:ttcIndex
        */
        public static int FontFamilyFont_android_ttcIndex = 3;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#font}
          attribute's value can be found in the {@link #FontFamilyFont} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.google.android.search.verification.client:font
        */
        public static int FontFamilyFont_font = 6;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontStyle}
          attribute's value can be found in the {@link #FontFamilyFont} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>italic</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.google.android.search.verification.client:fontStyle
        */
        public static int FontFamilyFont_fontStyle = 5;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontVariationSettings}
          attribute's value can be found in the {@link #FontFamilyFont} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:fontVariationSettings
        */
        public static int FontFamilyFont_fontVariationSettings = 8;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#fontWeight}
          attribute's value can be found in the {@link #FontFamilyFont} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:fontWeight
        */
        public static int FontFamilyFont_fontWeight = 7;
        /**
          <p>This symbol is the offset where the {@link com.google.android.search.verification.client.R.attr#ttcIndex}
          attribute's value can be found in the {@link #FontFamilyFont} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.search.verification.client:ttcIndex
        */
        public static int FontFamilyFont_ttcIndex = 9;
        /** Attributes that can be used with a GradientColor.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #GradientColor_android_centerColor android:centerColor}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_centerX android:centerX}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_centerY android:centerY}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_endColor android:endColor}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_endX android:endX}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_endY android:endY}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_gradientRadius android:gradientRadius}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_startColor android:startColor}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_startX android:startX}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_startY android:startY}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_tileMode android:tileMode}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColor_android_type android:type}</code></td><td></td></tr>
           </table>
           @see #GradientColor_android_centerColor
           @see #GradientColor_android_centerX
           @see #GradientColor_android_centerY
           @see #GradientColor_android_endColor
           @see #GradientColor_android_endX
           @see #GradientColor_android_endY
           @see #GradientColor_android_gradientRadius
           @see #GradientColor_android_startColor
           @see #GradientColor_android_startX
           @see #GradientColor_android_startY
           @see #GradientColor_android_tileMode
           @see #GradientColor_android_type
         */
        public static final int[] GradientColor = {
            0x0101019d, 0x0101019e, 0x010101a1, 0x010101a2,
            0x010101a3, 0x010101a4, 0x01010201, 0x0101020b,
            0x01010510, 0x01010511, 0x01010512, 0x01010513
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#centerColor}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:centerColor
        */
        public static int GradientColor_android_centerColor = 7;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#centerX}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:centerX
        */
        public static int GradientColor_android_centerX = 3;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#centerY}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:centerY
        */
        public static int GradientColor_android_centerY = 4;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#endColor}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:endColor
        */
        public static int GradientColor_android_endColor = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#endX}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:endX
        */
        public static int GradientColor_android_endX = 10;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#endY}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:endY
        */
        public static int GradientColor_android_endY = 11;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#gradientRadius}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:gradientRadius
        */
        public static int GradientColor_android_gradientRadius = 5;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#startColor}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:startColor
        */
        public static int GradientColor_android_startColor = 0;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#startX}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:startX
        */
        public static int GradientColor_android_startX = 8;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#startY}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:startY
        */
        public static int GradientColor_android_startY = 9;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#tileMode}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:tileMode
        */
        public static int GradientColor_android_tileMode = 6;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#type}
          attribute's value can be found in the {@link #GradientColor} array.
          @attr name android:type
        */
        public static int GradientColor_android_type = 2;
        /** Attributes that can be used with a GradientColorItem.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #GradientColorItem_android_color android:color}</code></td><td></td></tr>
           <tr><td><code>{@link #GradientColorItem_android_offset android:offset}</code></td><td></td></tr>
           </table>
           @see #GradientColorItem_android_color
           @see #GradientColorItem_android_offset
         */
        public static final int[] GradientColorItem = {
            0x010101a5, 0x01010514
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#color}
          attribute's value can be found in the {@link #GradientColorItem} array.
          @attr name android:color
        */
        public static int GradientColorItem_android_color = 0;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#offset}
          attribute's value can be found in the {@link #GradientColorItem} array.
          @attr name android:offset
        */
        public static int GradientColorItem_android_offset = 1;
    };
}
